#!/usr/bin/perl -w

use HTML::Entities;
use Getopt::Long;

GetOptions(
  'help'    => sub { usage() },
);


while (<>) {
  $_ = encode_entities($_);
  print;
}

sub usage {
  print <<'USAGE';
Usage: escapehtml [FILE]

Description:
Pass the input through `encode_entities` to escape away any characters with
special meaning in HTML. This produces an output safe to paste within the
source of an HTML document, which will render just as plain text.
USAGE

  exit 1;
}
