#!/usr/bin/perl

use strict;
use warnings;
use YAML;
use Getopt::Long qw(:config no_ignore_case);

GetOptions(
  'help'    => sub { usage() },
);

my $path = $ARGV[0] || ".";

opendir my $DIR, $path or die "Cannot open directory: $!";
my @file = readdir $DIR;
closedir $DIR;

my %ext;
for my $file (@file) {
  next unless $file =~ m/\./;
  next if $file =~ m/^\./;
  $file =~ s/^.+\.//;
  $ext{$file} = 1;
}

print "$_\n" for sort { $a cmp $b } keys %ext;

sub usage {
  print <<'USAGE';
Usage: exts [DIRECTORY]

Description:
Prints a list of all file extensions found in the specified DIRECTORY. By
default it lists extensions on the current directory.
USAGE

  exit 1;
}
