#!/usr/bin/perl

use strict;
use warnings;
use Getopt::Long;
use Term::ANSIColor;

# Hola, quise agregar esto

GetOptions(
  'help'    => sub { usage() },
);

my $many = @ARGV > 1;
while(<>) {
    next unless /[^[:space:][:print:]]/;
    s/([^[:space:][:print:]]+)/colored($1, 'on_red')/eg;
    print $ARGV, ": " if $many;
    print;
}

sub usage {
  print <<'USAGE';
Usage: gremlins [FILE1 ...]

Description:
From the given input files, or standard input if no file name is given,
output every line containing non-standard ASCII characters.
USAGE

  exit 1;
}
