#!/usr/bin/perl

use strict;
use warnings;
use Getopt::Long qw(:config no_ignore_case);

GetOptions(
  'help'    => sub { usage() },
);

while(<>) { print if /[^[:space:][:print:]]/ }

sub usage {
  print <<'USAGE';
Usage: gremlins [FILE1 ...]

Description:
From the given input files, or standard input if no file name is given, it
outputs every line containing non-standard ASCII characters.
USAGE

  exit 1;
}
