#!/usr/bin/perl

use strict;
use warnings;
use Getopt::Long;
use Math::BigFloat;

my $num = 10;

while (<>) {
  my $line = $_;
  my ($min, $max) = map { Math::BigFloat->new($_) } split(' ', $line, 2);
  print join("\t", $min, $max, nice_interval($min, $max, $num)), "\n";
}
exit 1;

sub nice_interval {
  my ($min, $max, $num) = @_;
  my $step = $max->copy()->bsub($min)->bdiv($num);
  my $exp = $step->copy()->blog(10)->bfloor();
  my $man = $step->copy()->bdiv(10 ** $exp)->bceil();
  if ($man > 5) { $man = 1; $exp->badd(1); } elsif ($man > 2) { $man = 5; }
  $step = Math::BigFloat->new("${man}E${exp}");
  my $a = $min->copy()->bdiv($step)->bfloor();
  my $bmax = $a->copy()->badd($num)->bmul($step);
  my $bmin = $a->copy()->bmul($step);
  my $e = $bmax->copy()->bsub($max)->bdiv($step)->bfloor();
#  $step->bmul(10 ** $exp);
  return ($step, $a, $bmin, $bmax, $e);
}

#  1 <= b <= 9
#  step = b*10^e
#  d1 = min - a*step
#  d2 = (a + n)*step - max
#  0 <= d1
#  0 <= d2
#  minimize: d1 + d2

#=========================

my $size = 10;
my $offset = 0;
my $min_i = undef;
my $u_min = undef;
my $u_max = undef;

GetOptions(
  "size=f"    => \$size,
  "offset=f"  => \$offset,
  "num=i"     => \$num,
  "min=f"     => \$u_min,
  "max=f"     => \$u_max,
  "help"      => sub { usage() },
);


my @hist;
my $stash = 0;
my @sample;
my $x_min = undef;
my $x_max = undef;

while (<>) {
  next if m/^\s*$/;
  my $x = Math::BigFloat->new($_);
  push @sample, $x;
  $x_min = min($x, $x_min);
  $x_max = max($x, $x_max);
  print join("\t", $x, log_round_up($x)), "\n";
}

print "min: $x_min\n";
print "max: $x_max\n";
exit 0;

#  my $i = to_bucket($x);
#  if ($i < 0) { $stash += 1; $i = 0; }
#  $min_i = min($i, $min_i);
#  $hist[$i]++;
#}

if ($stash) {
  my $new_offset = to_value(to_bucket($u_min));
  warn sprintf(
    "histogram: The first bucket includes $stash value%s bellow $offset\n" .
    "histogram: You may want to run again adding the option: --offset $new_offset\n",
    $stash > 1 ? "s" : "");
}

exit unless defined $min_i;

for my $i ($min_i..@hist - 1) {
  $hist[$i]+= 0;
  print "< ", to_value($i + 1), ":\t$hist[$i]\n";
}

sub min {
  my ($a, $b) = @_;
  return $a unless defined $b;
  return $b unless defined $a;
  return $a < $b ? $a : $b;
}

sub max {
  my ($a, $b) = @_;
  return $a unless defined $b;
  return $b unless defined $a;
  return $a > $b ? $a : $b;
}

sub to_bucket {
  my $x = shift @_;
  return int(($x - $offset)/$size);
}

sub to_value {
  my $i = shift @_;
  return $i*$size + $offset;
}

sub usage {
  print <<'USAGE';
Usage: histogram [options] [file]

Description:
Reads numeric data from `file' (or standard input if not supplied) and
produces a simple histogram of the data.

The following options are available:

--size NUM
  Size of each bucket in the histogram, defaults to 10.

--offset NUM
  Soft bound where the first bucket starts, defaults to 0. Values bellow
  the offset are still included in the count of the first bucket, but an
  informative warning is displayed.
  
USAGE

  exit 1;
}

# 