#!/usr/bin/env python
from bs4 import BeautifulSoup
import sys
import re
import csv

def cell_text(cell):
    return " ".join(cell.stripped_strings).encode('utf-8')

soup = BeautifulSoup(sys.stdin.read())
output = csv.writer(sys.stdout)
re_col = re.compile('t[dh]')

for table in soup.find_all('table'):
    for row in table.find_all('tr'):
        output.writerow([cell_text(cell) for cell in row.find_all(re_col)])
    output.writerow([])
