#!/usr/bin/perl

use strict;
use warnings;
use open qw/:std :utf8/;
use utf8;

my $template = "string://" . do {local $/; <DATA>};
my $file = shift @ARGV;

die "Usage: markpost FILE.md\n" unless
  defined $file && $file =~ m/\.md$/;
  
(my $outfile = $file) =~ s/\.md$/.html/;

open STDOUT, '>', $outfile or die "Can't open for writing: $outfile\n";
system('kramdown', '--template', $template, $file);

__DATA__
<!DOCTYPE HTML>
<html>
<head>
<title>Post draft</title>
<meta http-equiv="Content-Type" content="text/html;charset=UTF-8"/>
<style type="text/css">
article { border: black 1px solid; padding: 0 20px; width: 520px; margin: 20px auto; }
img { display: block; margin-left: auto; margin-right: auto }
</style>
</head>
<body>
<article>
<%= @body %>
</article>
</body>
