#!/bin/sh

while getopts :b opt
do case "$opt" in
  b) br="BR";;
  esac
done
shift $(($OPTIND - 1))

if [ "$br" == "BR" ]; then
  markdown $1 | smartypants | perl -nwe '{ s{<p>}{<br />\n}; s{</p>}{<br />}; print unless $_ =~ m{^\s*$} }'
else

  cat <<HEAD
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<title>Post draft</title>
<meta http-equiv="Content-Type" content="text/html;charset=UTF-8"/>
<style type="text/css">
img { display: block; margin-left: auto; margin-right: auto }
</style>
</head>
<body>
<div style="border: black 1px solid; padding: 0 20px; width: 520px; margin: 20px auto;">
HEAD

  markdown $1 | smartypants

  cat <<FOOT
</div>
</body>
FOOT

fi