#!/bin/sh

if (( $# != 2 )); then
  echo "Usage: merge OLD-FILE NEW-FILE"
  exit 1
fi

diff $1 $2 --old-group-format='<<<<<<< .old
%<=======
' --new-group-format='=======
%>>>>>>>> .new
' --changed-group-format='<<<<<<< .old
%<=======
%>>>>>>>> .new
'
