#!/usr/bin/env python
import os.path
import subprocess
import re
import sys
import yaml
from textwrap import dedent

class Scrapper:
    def __init__(self, config):
        lines = config.strip().split('\n')
        self._patterns = []
        for line in lines:
            pattern, value = line.strip().split('|')
            self._patterns.append((re.compile(pattern), value))
    
    def scrappe(self, output):
        notes = []
        ok_flag = False
        for pattern, value in self._patterns:
            if re.search(pattern, output):
                if value == '__ok__':
                    ok_flag = True
                else:
                    notes.append(value)
        if len(notes) == 0 and not ok_flag:
            print "== output =="
            print output
            raise StandardError('not enough patterns')
        return notes

gs = Scrapper('''
  Changes to be committed:|contains changes to be committed
  Changes not staged for commit:|contains changes in files
  Untracked files:|contains untracked files
  use "git push" to publish your local commits|contains local commits to push
  nothing to commit, working directory clean|__ok__
''')

def repo_check(path):
    full_path = os.path.expanduser(path)
    if not os.path.isdir(full_path):
        print path
        print "ERROR: Repository missing. To fix edit your config or run: pirate find"
        return False
    os.chdir(full_path)
    output = subprocess.check_output(['git', 'status'])
    branch = re.search('On branch (\w+)', output).group(1)
    notes = gs.scrappe(output)
    if notes:
        print '{} [{}]:'.format(path, branch)
        for note in notes:
            print '-', note
    return len(notes) == 0

def repo_pull(path):
    print path, '$ git pull'
    os.chdir(os.path.expanduser(path))
    output = subprocess.check_output(['git', 'pull'])
    print output

def save_map(filename, map):
    with open(os.path.expanduser(filename), 'w') as stream:
        stream.write(dedent("""\
            # This is pirate's list of git repositories found on your machie.
            # Directories listed under the `ignore` key, if any, have been ignored.
        """))
        yaml.safe_dump(map, stream, default_flow_style=False)

def load_map(filename):
    with open(os.path.expanduser(filename), 'r') as stream:
        map = yaml.safe_load(stream)
    return map
    
def build_index(map):
    index = {}
    ignore = set()
    if 'repositories' in map:
        for repository in map['repositories']:
            index[repository['path']] = repository
    if 'ignore' in map:
        for path in map['ignore']:
            ignore.add(path)
    return index, ignore

def repo_remote_url(path):
    cwd = os.getcwd()
    os.chdir(os.path.expanduser(path))
    remote = subprocess.check_output('git config --get remote.origin.url'.split()).strip()
    os.chdir(cwd)
    return remote

def build_map(filename, map=None):
    print "Finding git repositories under your home directory."
    print "Please be patient, this might take a while."
    print
    if map is None:
        map = {'repositories': []}        
    index, ignore = build_index(map)
    map['repositories'] = []
    new_found = 0
    os.chdir(os.path.expanduser('~'))
    for root, dirs, _ in os.walk('.'):
        path = '~' + root[1:]
        if path in ignore:
            del dirs[:]
            continue
        if '.git' in dirs:
            if path in index:
                map['repositories'].append(index[path])
                del index[path]
                status = 'active'
            else:
                new_found += 1
                map['repositories'].append({
                    'local': path, 
                    'remote': repo_remote_url(path)})
                status = '*new*'            
            print '{} [{}]'.format(path, status)
            dirs.remove('.git')
    if index:
        if not 'missing' in map:
            map['missing'] = []
        map['missing'].extend(list(index.values()))
        print
        print "The following repositories were missing and have been disabled:"
        for repository in index.keys():
            print "-", repository
    save_map(filename, map)
    print
    if new_found == 0:
        print "No new repositories were found."
    elif new_found == 1:
        print "1 new repository was found."
    else:
        print new_found, "new repositories were found."
    print
    print "Repository info has been written into:", filename
    print "Edit this file, if needed, and run pirate again."

pirate_config = '~/.pirate.yaml'
if not os.path.isfile(os.path.expanduser(pirate_config)):
    build_map(pirate_config)
    exit(0)

map = load_map(pirate_config)
save_map(pirate_config, map)
mode = sys.argv[1] if len(sys.argv) >= 2 else 'check'

if mode == 'find':
    build_map(pirate_config, map)
elif mode == 'check':
    all_clean = True
    for repository in map['repositories']:
        all_clean = repo_check(repository['local']) and all_clean
    if all_clean:
        print "All git repositories be spit shine. Arrr!"
elif mode == 'list':
    for repository in map['repositories']:
        print repository['local']
elif mode == 'pull':
    for repository in map['repositories']:
        repo_pull(repository['local'])
else:
    print "Unknown mode:", mode
    exit(1)
