#!/usr/bin/env python
import os.path
import subprocess
import re
import sys
import yaml

def find_repositories():
    print "Finding svn repositories under your home directory."
    print "Please be patient, this might take a while."
    print
    os.chdir(os.path.expanduser('~'))
    for root, dirs, _ in os.walk('.'):
        if '.svn' in dirs:
            path = '~' + root[1:]
            print path
            del dirs[:]

find_repositories()
