#!/usr/bin/perl -w

use strict;
use File::Slurp;
use HTTP::Response;

my $file = shift @ARGV;
die "Usage: webcontent WEB_FILE" unless defined $file;

my $resp = read_file($file, binmode => ':raw');
$resp = HTTP::Response->parse($resp);
die $resp->status_line . "\n" unless $resp->is_success;
print $resp->decoded_content;

exit 0;

__END__
my %mime_action = (
  'text/html'            => 'decoded:html',
  'text/javascript'      => 'decoded:js',
  'application/json'     => 'decoded:json',
  'application/atom+xml' => 'raw:xml',
  'image/jpeg'           => 'raw:jpeg'
);

my $type = $resp->content_type;
print "Mime type: $type\n";
die "Don't know what to do with this type\n" unless exists $mime_action{$type};

my ($act, $ext) = split ':', $mime_action{$type};
$file =~ s{\.web$}{};
$file .= ".$ext";

if ($act eq 'decoded') {
  write_file($file, $resp->decoded_content);
  print "Extracted: $file\n";
} elsif ($act eq 'raw') {
  write_file($file, { binmode => ':raw' }, $resp->content);
  print "Extracted: $file\n";
} else {
  die "Unknown action: $act";
}
